name: C++ Integration Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ python3-dev cmake
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pybind11 setuptools wheel pytest
    
    - name: Build C++ library
      run: |
        cd cpp
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)
    
    - name: Build Python bindings
      run: |
        cd cpp
        python setup.py build_ext --inplace
        # Ensure the module is in the cpp directory
        cp build/lib.*/drawing_cpp*.so . || true
    
    - name: Run C++ integration tests
      run: |
        export PYTHONPATH=${{ github.workspace }}:$PYTHONPATH
        cd ${{ github.workspace }}
        python tests/cpp_integration/run_tests.py